import type { Verdict } from "./types";

const TS = "2026-09-15T14:22:08Z";

export interface BlindCase {
  id: string;
  domain: string;
  source: string;
  expected: Verdict;
  rationale: string;
  payload: unknown;
}

export const BLIND_CASES: BlindCase[] = [
  {
    id: "B01",
    domain: "onboarding",
    source: "banque · collecte KYC",
    expected: "REPRENABLE",
    rationale: "Pièces numérisées, preuve scanner PASS, reste déclaré.",
    payload: {
      from: "kyc_scan",
      to: "analyst",
      task: "Collecter les pièces du dossier 4412",
      state: { known: { dossier_id: "4412" }, unknown: ["revenus hors bulletin"], version: "1" },
      work_done: [{ claim: "Les pièces d'identité ont été numérisées.", evidence_refs: ["s1"] }],
      work_remaining: ["Revue analyste"],
      evidence: [
        {
          id: "s1",
          type: "tool_result",
          source: "scanner_04",
          timestamp: TS,
          status: "PASS",
          content: { pages: 3, dpi: 300 },
        },
      ],
      uncertainties: ["Je ne sais pas si le justificatif de domicile a plus de 3 mois."],
    },
  },
  {
    id: "B02",
    domain: "données",
    source: "pipeline · extract quotidien",
    expected: "REPRENABLE",
    rationale: "Extraction chiffrée, checksum présent, chargement encore à faire.",
    payload: {
      from: "extractor",
      to: "loader",
      task: "Extraire le flux commandes du 15 septembre",
      state: { known: { table: "orders_raw", rows: 180_442 }, version: "7" },
      work_done: [{ claim: "L'extraction s'est terminée.", evidence_refs: ["x1"] }],
      work_remaining: ["Charger le warehouse"],
      evidence: [
        {
          id: "x1",
          type: "tool_result",
          source: "airflow",
          timestamp: TS,
          status: "PASS",
          content: { checksum: "sha256:9ab3", rows: 180442 },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "B03",
    domain: "paiements",
    source: "support · remboursement",
    expected: "REPRENABLE",
    rationale: "Remboursement versé, reçu PSP, notification restante.",
    payload: {
      from: "support",
      to: "notify",
      task: "Rembourser le ticket T-904",
      state: { known: { ticket: "T-904", amount: "64.00 EUR" }, version: "2" },
      work_done: [{ claim: "Le remboursement a été versé.", evidence_refs: ["rf1"] }],
      work_remaining: ["Prévenir le client"],
      evidence: [
        {
          id: "rf1",
          type: "transaction",
          source: "psp_adyen",
          timestamp: TS,
          status: "SUCCESS",
          content: { refund_id: "rf_22k" },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "B04",
    domain: "incident",
    source: "prod · worker paiements",
    expected: "REPRENABLE",
    rationale: "Logs collectés avec requête sourcée. Le correctif reste à écrire.",
    payload: {
      from: "sre",
      to: "planner",
      task: "Rassembler les journaux du worker-payments",
      state: { known: { service: "worker-payments", env: "prod" }, version: "1" },
      work_done: [{ claim: "Les journaux ont été collectés.", evidence_refs: ["l1"] }],
      work_remaining: ["Écrire le plan de correctif"],
      evidence: [
        {
          id: "l1",
          type: "document",
          source: "loki",
          timestamp: TS,
          status: "PASS",
          content: { query: "{app=worker-payments} |= mutex" },
        },
      ],
      uncertainties: ["Je ne sais pas si le phénomène n'apparaît que sous charge."],
    },
  },
  {
    id: "B05",
    domain: "crm",
    source: "campagne · validation de liste",
    expected: "REPRENABLE",
    rationale: "Liste validée par l'outil, envoi encore à faire.",
    payload: {
      from: "list_bot",
      to: "sender",
      task: "Valider la liste de la campagne mars",
      state: { known: { list_id: "nl_88", recipients: 12040 }, version: "3" },
      work_done: [{ claim: "La liste a été validée.", evidence_refs: ["v1"] }],
      work_remaining: ["Envoyer la campagne"],
      evidence: [
        {
          id: "v1",
          type: "tool_result",
          source: "list_hygiene",
          timestamp: TS,
          status: "PASS",
          content: { valid: 11890, suppressed: 150 },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "B06",
    domain: "juridique",
    source: "contrat · extraction de clause",
    expected: "REPRENABLE",
    rationale: "Clause extraite avec empreinte document. Confirmation humaine restante.",
    payload: {
      from: "parser",
      to: "counsel",
      task: "Extraire la clause de résiliation du contrat C-17",
      state: { known: { contract: "C-17" }, version: "1" },
      work_done: [{ claim: "La clause a été extraite.", evidence_refs: ["d1"] }],
      work_remaining: ["Confirmation du juriste"],
      evidence: [
        {
          id: "d1",
          type: "document",
          source: "parser_11",
          timestamp: TS,
          status: "PASS",
          content: { page: 14, content_hash: "sha256:c17a" },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "B07",
    domain: "logistique",
    source: "entrepôt · inventaire",
    expected: "REPRENABLE",
    rationale: "Comptage WMS présent. Réassort encore ouvert.",
    payload: {
      from: "wms",
      to: "buyer",
      task: "Comptage du SKU-440",
      state: { known: { sku: "SKU-440", bin: "A-12" }, version: "4" },
      work_done: [{ claim: "Le stock a été compté.", evidence_refs: ["w1"] }],
      work_remaining: ["Décider le réassort"],
      evidence: [
        {
          id: "w1",
          type: "tool_result",
          source: "wms_snapshot",
          timestamp: TS,
          status: "PASS",
          content: { on_hand: 18 },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "B08",
    domain: "recherche",
    source: "MCP · note réglementaire",
    expected: "REPRENABLE",
    rationale: "Même objet, enveloppé. Incertitude déclarée, pas cachée.",
    payload: {
      method: "handoff.certify",
      params: {
        from: "researcher",
        to: "writer",
        task: "Cartographier le régime applicable au cas 12b",
        state: { known: { jurisdiction: "EU" }, unknown: ["interprétation locale"], version: "2" },
        work_done: [{ claim: "Les sources primaires ont été collectées.", evidence_refs: ["src1"] }],
        work_remaining: ["Rédiger la note"],
        evidence: [
          {
            id: "src1",
            type: "document",
            source: "eur-lex",
            timestamp: TS,
            status: "PASS",
            content: { eli: "reg/2016/679" },
          },
        ],
        uncertainties: ["Je ne sais pas si le considérant 47 s'applique ici."],
      },
    },
  },
  {
    id: "B09",
    domain: "ci",
    source: "déploiement · fragment réel",
    expected: "PARTIEL",
    rationale: "« tests exécutés » n'est pas une preuve. Le reste est déclaré.",
    payload: {
      from: "implementer",
      to: "deployer",
      task: "Préparer le déploiement",
      work_done: ["tests exécutés"],
      evidence: [],
      work_remaining: ["déployer"],
    },
  },
  {
    id: "B10",
    domain: "support",
    source: "ticket · clôture",
    expected: "PARTIEL",
    rationale: "Preuve présente, travail restant non déclaré.",
    payload: {
      from: "agent",
      to: "supervisor",
      task: "Traiter le ticket INC-22",
      state: { known: { ticket: "INC-22" }, version: "3" },
      work_done: [{ claim: "La réponse a été envoyée.", evidence_refs: ["m1"] }],
      evidence: [
        {
          id: "m1",
          type: "tool_result",
          source: "zendesk",
          timestamp: TS,
          status: "PASS",
          content: { message_id: "msg_90" },
        },
      ],
    },
  },
  {
    id: "B11",
    domain: "ops",
    source: "réunion · compte rendu",
    expected: "PARTIEL",
    rationale: "Le compte rendu est affirmé. Aucune pièce jointe.",
    payload: {
      from: "secretary",
      to: "team",
      task: "Rédiger le compte rendu du comité",
      state: { known: { meeting: "COM-09" }, version: "1" },
      work_done: [{ claim: "Le compte rendu a été rédigé.", evidence_refs: [] }],
      work_remaining: ["Diffuser aux participants"],
      evidence: [],
      uncertainties: [],
    },
  },
  {
    id: "B12",
    domain: "onboarding",
    source: "client · adresse",
    expected: "PARTIEL",
    rationale: "Adresse déclarée vérifiée, sans source.",
    payload: {
      from: "form",
      to: "kyc",
      task: "Vérifier l'adresse postale",
      state: { known: { customer_id: "cu_19" }, version: "1" },
      work_done: [{ claim: "L'adresse a été vérifiée.", evidence_refs: [] }],
      work_remaining: ["Poursuivre le dossier"],
      evidence: [],
    },
  },
  {
    id: "B13",
    domain: "ingénierie",
    source: "hotfix · revue",
    expected: "PARTIEL",
    rationale: "Trois affirmations, une seule reliée.",
    payload: {
      from: "implementer",
      to: "reviewer",
      task: "Livrer le correctif mutex",
      state: { known: { branch: "hotfix/lock" }, version: "2" },
      work_done: [
        { claim: "Le correctif a été écrit.", evidence_refs: ["c1"] },
        { claim: "Les tests ont été exécutés.", evidence_refs: [] },
        { claim: "La documentation a été mise à jour.", evidence_refs: [] },
      ],
      work_remaining: ["Revue"],
      evidence: [
        {
          id: "c1",
          type: "commit",
          source: "git",
          timestamp: TS,
          status: "PASS",
          content: { sha: "ab12cd" },
        },
      ],
    },
  },
  {
    id: "B14",
    domain: "finance",
    source: "facture · référence morte",
    expected: "PARTIEL",
    rationale: "L'affirmation pointe vers une preuve absente.",
    payload: {
      from: "billing",
      to: "archive",
      task: "Émettre la facture F-220",
      state: { known: { invoice: "F-220" }, version: "1" },
      work_done: [{ claim: "La facture a été émise.", evidence_refs: ["inv99"] }],
      work_remaining: ["Archiver"],
      evidence: [
        {
          id: "inv1",
          type: "document",
          source: "erp",
          timestamp: TS,
          status: "PASS",
          content: { number: "F-220" },
        },
      ],
    },
  },
  {
    id: "B15",
    domain: "ops",
    source: "file d'attente · objectif manquant",
    expected: "PARTIEL",
    rationale: "Sans objectif, l'agent suivant reconstruit le but.",
    payload: {
      from: "queue",
      to: "worker",
      task: "",
      state: { known: { job: "j_8" }, version: "1" },
      work_done: [{ claim: "Le lot a été préparé.", evidence_refs: ["p1"] }],
      work_remaining: ["Exécuter le lot"],
      evidence: [
        {
          id: "p1",
          type: "tool_result",
          source: "batcher",
          timestamp: TS,
          status: "PASS",
          content: { items: 40 },
        },
      ],
    },
  },
  {
    id: "B16",
    domain: "voyage",
    source: "concierge · hôtel",
    expected: "PARTIEL",
    rationale: "Réservation affirmée, aucune confirmation GDS.",
    payload: {
      from: "travel",
      to: "concierge",
      task: "Réserver l'hôtel à Lyon",
      state: { known: { city: "Lyon", nights: 2 }, version: "1" },
      work_done: [{ claim: "La réservation a été confirmée.", evidence_refs: [] }],
      work_remaining: ["Envoyer l'itinéraire"],
      evidence: [],
    },
  },
  {
    id: "B17",
    domain: "paiements",
    source: "checkout · encaissement",
    expected: "CORROMPU",
    rationale: "Affirme un versement. La transaction est CANCELLED.",
    payload: {
      from: "checkout",
      to: "fulfillment",
      task: "Encaisser la commande 8821",
      state: { known: { order_id: "8821" }, version: "1" },
      work_done: [{ claim: "Paiement effectué.", evidence_refs: ["tx1"] }],
      work_remaining: ["Expédier"],
      evidence: [
        {
          id: "tx1",
          type: "transaction",
          source: "psp",
          timestamp: TS,
          status: "CANCELLED",
          content: { transaction_id: "ch_9f2a" },
        },
      ],
    },
  },
  {
    id: "B18",
    domain: "iam",
    source: "accès · provisionnement",
    expected: "CORROMPU",
    rationale: "Affirme un accès accordé. IAM répond DENIED.",
    payload: {
      from: "iam_bot",
      to: "itops",
      task: "Ouvrir l'accès staging pour l'ingénieur 17",
      state: { known: { user: "eng_17", role: "staging-reader" }, version: "1" },
      work_done: [{ claim: "L'accès a été approuvé.", evidence_refs: ["iam1"] }],
      work_remaining: ["Notifier le demandeur"],
      evidence: [
        {
          id: "iam1",
          type: "tool_result",
          source: "okta",
          timestamp: TS,
          status: "DENIED",
          content: { reason: "group_missing" },
        },
      ],
    },
  },
  {
    id: "B19",
    domain: "ci",
    source: "pipeline · compilation",
    expected: "CORROMPU",
    rationale: "Affirme une compilation réussie. La CI dit FAIL.",
    payload: {
      from: "builder",
      to: "reviewer",
      task: "Compiler la branche hotfix/lock",
      state: { known: { sha: "ab12cd" }, version: "4" },
      work_done: [{ claim: "La compilation a réussi.", evidence_refs: ["ci1"] }],
      work_remaining: ["Revue"],
      evidence: [
        {
          id: "ci1",
          type: "tool_result",
          source: "github-actions",
          timestamp: TS,
          status: "FAIL",
          content: { job: "build" },
        },
      ],
    },
  },
  {
    id: "B20",
    domain: "qualité",
    source: "double validation",
    expected: "CORROMPU",
    rationale: "Deux preuves pour la même affirmation : PASS et FAIL.",
    payload: {
      from: "qa",
      to: "release",
      task: "Valider le paquet 1.8.4",
      state: { known: { release: "1.8.4" }, version: "1" },
      work_done: [{ claim: "Le paquet a été validé.", evidence_refs: ["e1", "e2"] }],
      work_remaining: ["Publier"],
      evidence: [
        {
          id: "e1",
          type: "tool_result",
          source: "qa_east",
          timestamp: TS,
          status: "PASS",
          content: { gate: "smoke" },
        },
        {
          id: "e2",
          type: "tool_result",
          source: "qa_west",
          timestamp: TS,
          status: "FAIL",
          content: { gate: "smoke" },
        },
      ],
    },
  },
  {
    id: "B21",
    domain: "logistique",
    source: "expédition · transporteur",
    expected: "CORROMPU",
    rationale: "Affirme une expédition. Le transporteur a rejeté l'étiquette.",
    payload: {
      from: "warehouse",
      to: "customer_ops",
      task: "Expédier la commande 8821",
      state: { known: { order_id: "8821" }, version: "2" },
      work_done: [{ claim: "L'expédition a été confirmée.", evidence_refs: ["sh1"] }],
      work_remaining: ["Suivre la livraison"],
      evidence: [
        {
          id: "sh1",
          type: "booking",
          source: "carrier_api",
          timestamp: TS,
          status: "REJECTED",
          content: { reason: "invalid_postcode" },
        },
      ],
    },
  },
  {
    id: "B22",
    domain: "onboarding",
    source: "LangGraph · reprise KYC",
    expected: "REPRENABLE",
    rationale: "Enveloppe framework. L'objet interne est complet.",
    payload: {
      next: "analyst",
      state: { dossier_id: "4412" },
      handoff: {
        from: "kyc_scan",
        to: "analyst",
        task: "Collecter les pièces du dossier 4412",
        state: { known: { dossier_id: "4412" }, version: "1" },
        work_done: [{ claim: "Les pièces d'identité ont été numérisées.", evidence_refs: ["s1"] }],
        work_remaining: ["Revue analyste"],
        evidence: [
          {
            id: "s1",
            type: "tool_result",
            source: "scanner_04",
            timestamp: TS,
            status: "PASS",
            content: { pages: 3 },
          },
        ],
        uncertainties: [],
      },
    },
  },
];

export const BLIND_ORDER = [
  "B09",
  "B01",
  "B17",
  "B10",
  "B02",
  "B18",
  "B11",
  "B03",
  "B19",
  "B12",
  "B04",
  "B20",
  "B13",
  "B05",
  "B21",
  "B14",
  "B06",
  "B22",
  "B15",
  "B07",
  "B16",
  "B08",
] as const;

export function orderedBlindCases(): BlindCase[] {
  return BLIND_ORDER.map((id) => BLIND_CASES.find((c) => c.id === id)!);
}
