import type { BenchCase } from "./types";

const TS = "2026-09-16T08:41:12Z";

const fileEvidence = {
  id: "e1",
  type: "tool_result",
  source: "validator_17",
  timestamp: TS,
  status: "PASS",
  content: { validation_result: "PASS", file: "report.pdf" },
};

const cleanValidation = {
  from: "agent_A",
  to: "agent_B",
  task: {
    objective: "Valider le fichier client avant transmission",
    constraints: ["Ne pas modifier le fichier"],
  },
  state: {
    known: { file: "report.pdf", size_bytes: 241_112 },
    unknown: [],
    version: "1",
  },
  work_done: [
    {
      claim: "Le fichier a été validé.",
      evidence_refs: ["e1"],
    },
  ],
  work_remaining: ["Transmettre le fichier à l'archivage"],
  evidence: [fileEvidence],
  uncertainties: [],
};

export const BENCH_CASES: BenchCase[] = [
  {
    id: "clean_validation",
    title: "Validation de fichier",
    category: "positif",
    framework: "canonical",
    description: "Affirmation reliée à une preuve PASS, horodatée et sourcée.",
    expected: "REPRENABLE",
    payload: cleanValidation,
  },
  {
    id: "payment_ok",
    title: "Paiement confirmé",
    category: "positif",
    framework: "canonical",
    description: "Transaction identifiée, statut SUCCESS, suite de travail déclarée.",
    expected: "REPRENABLE",
    payload: {
      from: "billing",
      to: "fulfillment",
      task: "Encaisser la commande 8821",
      state: { known: { order_id: "8821", amount: "120.00 EUR" }, version: "3" },
      work_done: [{ claim: "Paiement effectué.", evidence_refs: ["tx1"] }],
      work_remaining: ["Émettre la facture"],
      evidence: [
        {
          id: "tx1",
          type: "transaction",
          source: "psp_stripe",
          timestamp: TS,
          status: "SUCCESS",
          content: { transaction_id: "ch_9f2a", amount: 12000 },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "research_handoff",
    title: "Recherche sourcée",
    category: "positif",
    framework: "canonical",
    description: "Travail de recherche avec sources, restes et incertitudes déclarées.",
    expected: "REPRENABLE",
    payload: {
      from: "researcher",
      to: "writer",
      task: { objective: "Cartographier les risques réglementaires" },
      state: {
        known: { jurisdiction: "EU" },
        unknown: ["interprétation locale FR"],
        version: "2",
      },
      work_done: [
        {
          claim: "Les sources primaires ont été collectées.",
          evidence_refs: ["src1"],
        },
      ],
      work_remaining: ["Rédiger la note de synthèse"],
      evidence: [
        {
          id: "src1",
          type: "document",
          source: "eur-lex",
          timestamp: TS,
          status: "PASS",
          content: { url: "https://eur-lex.europa.eu/eli/reg/2016/679/oj" },
        },
      ],
      uncertainties: ["Je ne sais pas si X s'applique au cas 12b."],
    },
  },
  {
    id: "honest_start",
    title: "Démarrage honnête",
    category: "positif",
    framework: "canonical",
    description: "Rien n'est revendiqué. Tâche, état et reste sont déclarés.",
    expected: "REPRENABLE",
    payload: {
      from: "orchestrator",
      to: "agent_A",
      task: "Ouvrir le dossier client 4412",
      state: {
        known: { dossier_id: "4412" },
        unknown: ["préférences de contact"],
        version: "1",
      },
      work_done: [],
      work_remaining: ["Collecter les pièces", "Vérifier l'éligibilité"],
      evidence: [],
      uncertainties: [],
    },
  },
  {
    id: "code_review_pass",
    title: "Revue de code",
    category: "positif",
    framework: "canonical",
    description: "Tests unitaires passés, preuve outil, source CI.",
    expected: "REPRENABLE",
    payload: {
      from: "implementer",
      to: "reviewer",
      task: { objective: "Corriger le deadlock du worker" },
      state: { known: { branch: "hotfix/lock", sha: "a1b2c3d" }, version: "4" },
      work_done: [{ claim: "Les tests sont passés.", evidence_refs: ["ci1"] }],
      work_remaining: ["Revue humaine du diff"],
      evidence: [
        {
          id: "ci1",
          type: "tool_result",
          source: "github-actions",
          timestamp: TS,
          status: "PASS",
          content: { suite: "unit", passed: 41, failed: 0 },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "booking_confirmed",
    title: "Réservation confirmée",
    category: "positif",
    framework: "canonical",
    description: "Numéro de confirmation, source GDS, horodatage.",
    expected: "REPRENABLE",
    payload: {
      from: "travel_agent",
      to: "concierge",
      task: "Réserver l'hôtel pour la mission Lyon",
      state: { known: { city: "Lyon", nights: 2 }, version: "1" },
      work_done: [{ claim: "La réservation a été confirmée.", evidence_refs: ["bk1"] }],
      work_remaining: ["Envoyer l'itinéraire au voyageur"],
      evidence: [
        {
          id: "bk1",
          type: "booking",
          source: "gds_amadeus",
          timestamp: TS,
          status: "CONFIRMED",
          content: { confirmation: "LYS-44190" },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "declared_uncertainty",
    title: "Incertitude explicite",
    category: "positif",
    framework: "canonical",
    description: "Un bon transfert dit ce qu'il ne sait pas. Ce n'est pas une corruption.",
    expected: "REPRENABLE",
    payload: {
      from: "analyst",
      to: "decision",
      task: { objective: "Établir la solvabilité du compte" },
      state: { known: { account_id: "ac_22" }, unknown: ["dettes hors bilan"], version: "1" },
      work_done: [{ claim: "Le score interne a été calculé.", evidence_refs: ["sc1"] }],
      work_remaining: ["Décision d'octroi"],
      evidence: [
        {
          id: "sc1",
          type: "tool_result",
          source: "risk_engine",
          timestamp: TS,
          status: "PASS",
          content: { score: 712 },
        },
      ],
      uncertainties: ["Je ne sais pas si le client a déjà un compte ailleurs."],
    },
  },
  {
    id: "complete_work",
    title: "Travail achevé",
    category: "positif",
    framework: "canonical",
    description: "Toutes les étapes sont prouvées. Le reste est une liste vide.",
    expected: "REPRENABLE",
    payload: {
      from: "closer",
      to: "archive",
      task: "Clôturer le ticket INC-90",
      state: { known: { ticket: "INC-90" }, version: "9" },
      work_done: [
        { claim: "Le correctif a été déployé.", evidence_refs: ["d1"] },
        { claim: "La vérification a été effectuée.", evidence_refs: ["d2"] },
      ],
      work_remaining: [],
      evidence: [
        {
          id: "d1",
          type: "deploy",
          source: "argo",
          timestamp: TS,
          status: "PASS",
          content: { release: "1.8.4" },
        },
        {
          id: "d2",
          type: "tool_result",
          source: "probe",
          timestamp: TS,
          status: "PASS",
          content: { health: "ok" },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "claim_no_evidence",
    title: "Affirmation sans preuve",
    category: "partiel",
    framework: "canonical",
    description: "« J'ai terminé » n'est pas une preuve.",
    expected: "PARTIEL",
    payload: {
      from: "agent_A",
      to: "agent_B",
      task: "Valider le fichier",
      state: { known: { file: "report.pdf" }, version: "1" },
      work_done: [{ claim: "Le fichier a été validé.", evidence_refs: [] }],
      work_remaining: ["Archiver"],
      evidence: [],
      uncertainties: [],
    },
  },
  {
    id: "remaining_unknown",
    title: "Reste inconnu",
    category: "partiel",
    framework: "canonical",
    description: "Les preuves sont là, mais le travail restant n'est pas déclaré.",
    expected: "PARTIEL",
    payload: {
      from: "agent_A",
      to: "agent_B",
      task: "Valider le fichier",
      state: { known: { file: "report.pdf" }, version: "1" },
      work_done: [{ claim: "Le fichier a été validé.", evidence_refs: ["e1"] }],
      evidence: [fileEvidence],
      uncertainties: [],
    },
  },
  {
    id: "missing_objective",
    title: "Tâche absente",
    category: "partiel",
    framework: "canonical",
    description: "Sans objectif, l'agent suivant doit reconstruire le but.",
    expected: "PARTIEL",
    payload: {
      from: "agent_A",
      to: "agent_B",
      task: "",
      state: { known: { file: "report.pdf" }, version: "1" },
      work_done: [{ claim: "Le fichier a été validé.", evidence_refs: ["e1"] }],
      work_remaining: ["Archiver"],
      evidence: [fileEvidence],
      uncertainties: [],
    },
  },
  {
    id: "dangling_ref",
    title: "Référence morte",
    category: "partiel",
    framework: "canonical",
    description: "L'affirmation pointe vers une preuve qui n'existe pas.",
    expected: "PARTIEL",
    payload: {
      from: "agent_A",
      to: "agent_B",
      task: "Valider le fichier",
      state: { known: { file: "report.pdf" }, version: "1" },
      work_done: [{ claim: "Le fichier a été validé.", evidence_refs: ["e99"] }],
      work_remaining: ["Archiver"],
      evidence: [fileEvidence],
      uncertainties: [],
    },
  },
  {
    id: "critical_missing",
    title: "Étape critique sans preuve",
    category: "partiel",
    framework: "canonical",
    description: "Une affirmation marquée critique n'a aucune preuve.",
    expected: "PARTIEL",
    payload: {
      from: "agent_A",
      to: "agent_B",
      task: { objective: "Autoriser le virement", critical: true },
      state: { known: { amount: "40_000 EUR" }, version: "1" },
      work_done: [
        { claim: "Le virement a été autorisé.", evidence_refs: [], critical: true },
      ],
      work_remaining: ["Notifier le bénéficiaire"],
      evidence: [],
      uncertainties: [],
    },
  },
  {
    id: "partial_chain",
    title: "Chaîne incomplète",
    category: "partiel",
    framework: "canonical",
    description: "Trois affirmations, une seule reliée à une preuve.",
    expected: "PARTIEL",
    payload: {
      from: "implementer",
      to: "reviewer",
      task: "Livrer le correctif",
      state: { known: { ticket: "INC-12" }, version: "2" },
      work_done: [
        { claim: "Le correctif a été écrit.", evidence_refs: ["c1"] },
        { claim: "Les tests sont passés.", evidence_refs: [] },
        { claim: "La documentation a été mise à jour.", evidence_refs: [] },
      ],
      work_remaining: ["Revue"],
      evidence: [
        {
          id: "c1",
          type: "commit",
          source: "git",
          timestamp: TS,
          status: "PASS",
          content: { sha: "deadbeef" },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "payment_cancelled",
    title: "Paiement annulé",
    category: "corrompu",
    framework: "canonical",
    description: "Affirme « effectué » alors que la transaction est CANCELLED.",
    expected: "CORROMPU",
    payload: {
      from: "billing",
      to: "fulfillment",
      task: "Encaisser la commande 8821",
      state: { known: { order_id: "8821" }, version: "3" },
      work_done: [{ claim: "Paiement effectué.", evidence_refs: ["tx1"] }],
      work_remaining: ["Expédier"],
      evidence: [
        {
          id: "tx1",
          type: "transaction",
          source: "psp_stripe",
          timestamp: TS,
          status: "CANCELLED",
          content: { transaction_id: "ch_9f2a" },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "tests_failed",
    title: "Tests échoués",
    category: "corrompu",
    framework: "canonical",
    description: "Affirme que les tests sont passés. La CI dit FAIL.",
    expected: "CORROMPU",
    payload: {
      from: "implementer",
      to: "reviewer",
      task: "Corriger le deadlock",
      state: { known: { branch: "hotfix/lock" }, version: "4" },
      work_done: [{ claim: "Les tests sont passés.", evidence_refs: ["ci1"] }],
      work_remaining: ["Revue"],
      evidence: [
        {
          id: "ci1",
          type: "tool_result",
          source: "github-actions",
          timestamp: TS,
          status: "FAIL",
          content: { passed: 38, failed: 3 },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "review_rejected",
    title: "Revue rejetée",
    category: "corrompu",
    framework: "canonical",
    description: "Affirme une approbation. La preuve dit REJECTED.",
    expected: "CORROMPU",
    payload: {
      from: "reviewer",
      to: "deployer",
      task: "Autoriser le déploiement production",
      state: { known: { sha: "a1b2c3d" }, version: "5" },
      work_done: [{ claim: "La revue a été approuvée.", evidence_refs: ["rv1"] }],
      work_remaining: ["Déployer"],
      evidence: [
        {
          id: "rv1",
          type: "review",
          source: "reviewer_9",
          timestamp: TS,
          status: "REJECTED",
          content: { reason: "missing rollback" },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "false_success",
    title: "Validation contredite",
    category: "corrompu",
    framework: "canonical",
    description: "Le contenu de la preuve nie l'affirmation.",
    expected: "CORROMPU",
    payload: {
      from: "agent_A",
      to: "agent_B",
      task: "Valider le fichier",
      state: { known: { file: "report.pdf" }, version: "1" },
      work_done: [{ claim: "Le fichier a été validé.", evidence_refs: ["e1"] }],
      work_remaining: ["Archiver"],
      evidence: [
        {
          id: "e1",
          type: "tool_result",
          source: "validator_17",
          timestamp: TS,
          status: "FAIL",
          content: { validation_result: "FAIL" },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "dual_evidence_conflict",
    title: "Preuves opposées",
    category: "corrompu",
    framework: "canonical",
    description: "Deux preuves pour la même affirmation : PASS et FAIL.",
    expected: "CORROMPU",
    payload: {
      from: "agent_A",
      to: "agent_B",
      task: "Valider le fichier",
      state: { known: { file: "report.pdf" }, version: "1" },
      work_done: [{ claim: "Le fichier a été validé.", evidence_refs: ["e1", "e2"] }],
      work_remaining: ["Archiver"],
      evidence: [
        fileEvidence,
        {
          id: "e2",
          type: "tool_result",
          source: "validator_18",
          timestamp: TS,
          status: "FAIL",
          content: { validation_result: "FAIL" },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "empty_package",
    title: "Paquet vide",
    category: "adversarial",
    framework: "canonical",
    description: "Rien à reprendre. Incomplet, pas corrompu.",
    expected: "PARTIEL",
    payload: {},
  },
  {
    id: "extra_unused_evidence",
    title: "Preuve superflue",
    category: "adversarial",
    framework: "canonical",
    description: "Preuve non reliée. Le paquet reste reprenable.",
    expected: "REPRENABLE",
    payload: {
      ...cleanValidation,
      evidence: [
        fileEvidence,
        {
          id: "e_unused",
          type: "note",
          source: "logger",
          timestamp: TS,
          status: "PASS",
          content: "trace annexée",
        },
      ],
    },
  },
  {
    id: "reformulation_en",
    title: "Reformulation anglaise",
    category: "adversarial",
    framework: "canonical",
    description: "Même propriété, autre langue. Le moteur ne lit pas le style.",
    expected: "REPRENABLE",
    payload: {
      from: "agent_A",
      to: "agent_B",
      task: "Validate the client file before transmission",
      state: { known: { file: "report.pdf" }, version: "1" },
      work_done: [{ claim: "The file has been validated.", evidence_refs: ["e1"] }],
      work_remaining: ["Transmit the file to archive"],
      evidence: [fileEvidence],
      uncertainties: [],
    },
  },
  {
    id: "mcp_envelope",
    title: "Enveloppe MCP",
    category: "adversarial",
    framework: "mcp",
    description: "Même objet, enveloppé dans params. L'adaptateur doit normaliser.",
    expected: "REPRENABLE",
    payload: {
      method: "handoff.certify",
      params: cleanValidation,
    },
  },
  {
    id: "future_timestamp",
    title: "Horodatage futur",
    category: "adversarial",
    framework: "canonical",
    description: "Avertissement de fraîcheur, pas une corruption.",
    expected: "REPRENABLE",
    payload: {
      ...cleanValidation,
      evidence: [
        {
          ...fileEvidence,
          timestamp: "2027-01-01T00:00:00Z",
        },
      ],
    },
  },
];

export const FEATURED_CASES = [
  "clean_validation",
  "claim_no_evidence",
  "payment_cancelled",
] as const;

export function getCase(id: string): BenchCase | undefined {
  return BENCH_CASES.find((c) => c.id === id);
}

export const TRACE_CHAIN: Array<{
  id: string;
  from: string;
  to: string;
  role: string;
  payload: unknown;
}> = [
  {
    id: "H1",
    from: "researcher",
    to: "planner",
    role: "Cartographier l'incident",
    payload: {
      from: "researcher",
      to: "planner",
      task: "Diagnostiquer le deadlock du worker de production",
      state: {
        known: { service: "worker-payments", env: "prod" },
        unknown: ["repro hors heures"],
        version: "1",
      },
      work_done: [
        { claim: "Les sources de logs ont été collectées.", evidence_refs: ["l1"] },
      ],
      work_remaining: ["Écrire le plan de correctif"],
      evidence: [
        {
          id: "l1",
          type: "document",
          source: "loki",
          timestamp: TS,
          status: "PASS",
          content: { query: "{app=worker-payments} |= deadlock" },
        },
      ],
      uncertainties: ["Je ne sais pas si le lock survient uniquement sous charge."],
    },
  },
  {
    id: "H2",
    from: "planner",
    to: "implementer",
    role: "Planifier le correctif",
    payload: {
      from: "planner",
      to: "implementer",
      task: "Produire un plan de correctif pour le deadlock",
      state: {
        known: { root_cause: "mutex inversé dans ack()", branch: "hotfix/lock" },
        unknown: [],
        version: "2",
      },
      work_done: [{ claim: "Le plan a été validé.", evidence_refs: ["p1"] }],
      work_remaining: ["Implémenter le correctif", "Ajouter un test de course"],
      evidence: [
        {
          id: "p1",
          type: "document",
          source: "planner_3",
          timestamp: TS,
          status: "PASS",
          content: { steps: 4, rollback: true },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "H3",
    from: "implementer",
    to: "reviewer",
    role: "Implémenter",
    payload: {
      from: "implementer",
      to: "reviewer",
      task: "Implémenter le correctif deadlock",
      state: { known: { sha: "c0ffee" }, version: "3" },
      work_done: [
        { claim: "Le correctif a été écrit.", evidence_refs: ["c1"] },
        { claim: "Les tests sont passés.", evidence_refs: [] },
      ],
      work_remaining: ["Revue"],
      evidence: [
        {
          id: "c1",
          type: "commit",
          source: "git",
          timestamp: TS,
          status: "PASS",
          content: { sha: "c0ffee" },
        },
      ],
      uncertainties: [],
    },
  },
  {
    id: "H4",
    from: "reviewer",
    to: "deployer",
    role: "Autoriser le déploiement",
    payload: {
      from: "reviewer",
      to: "deployer",
      task: "Autoriser le déploiement production",
      state: { known: { sha: "c0ffee" }, version: "4" },
      work_done: [{ claim: "La revue a été approuvée.", evidence_refs: ["rv1"] }],
      work_remaining: ["Déployer"],
      evidence: [
        {
          id: "rv1",
          type: "review",
          source: "reviewer_9",
          timestamp: TS,
          status: "REJECTED",
          content: { reason: "tests absents du paquet" },
        },
      ],
      uncertainties: [],
    },
  },
];

export const MATRIX: Array<{ condition: string; result: string }> = [
  { condition: "État absent mais inutile", result: "REPRENABLE possible" },
  { condition: "Preuve absente, tâche non critique", result: "PARTIEL" },
  { condition: "Preuve absente, tâche critique", result: "PARTIEL" },
  { condition: "Contradiction état / preuve", result: "CORROMPU" },
  { condition: "Travail restant inconnu", result: "PARTIEL" },
  { condition: "Incertitude explicitement déclarée", result: "pas forcément mauvais" },
  { condition: "Incertitude cachée (affirmation sans preuve)", result: "PARTIEL" },
  { condition: "Affirmation + preuve cohérente", result: "positif" },
  { condition: "Affirmation + preuve contradictoire", result: "CORROMPU" },
];
