/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdoptRouteImport } from './routes/adopt'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as BlindRouteImport } from './routes/blind'
import { Route as CertifyRouteImport } from './routes/certify'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CorpusRouteImport } from './routes/corpus'
import { Route as FalsifyRouteImport } from './routes/falsify'
import { Route as FormatRouteImport } from './routes/format'
import { Route as GotoRouteImport } from './routes/goto'
import { Route as InvariantsRouteImport } from './routes/invariants'
import { Route as MarqueursRouteImport } from './routes/marqueurs'
import { Route as OffreRouteImport } from './routes/offre'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as PreuveRouteImport } from './routes/preuve'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ShaRouteImport } from './routes/sha'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as TraceRouteImport } from './routes/trace'
import { Route as ApiV1CertifyRouteImport } from './routes/api/v1/certify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptRoute = AdoptRouteImport.update({
  id: '/adopt',
  path: '/adopt',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const BlindRoute = BlindRouteImport.update({
  id: '/blind',
  path: '/blind',
  getParentRoute: () => rootRouteImport,
} as any)
const CertifyRoute = CertifyRouteImport.update({
  id: '/certify',
  path: '/certify',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusRoute = CorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => rootRouteImport,
} as any)
const FalsifyRoute = FalsifyRouteImport.update({
  id: '/falsify',
  path: '/falsify',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatRoute = FormatRouteImport.update({
  id: '/format',
  path: '/format',
  getParentRoute: () => rootRouteImport,
} as any)
const GotoRoute = GotoRouteImport.update({
  id: '/goto',
  path: '/goto',
  getParentRoute: () => rootRouteImport,
} as any)
const InvariantsRoute = InvariantsRouteImport.update({
  id: '/invariants',
  path: '/invariants',
  getParentRoute: () => rootRouteImport,
} as any)
const MarqueursRoute = MarqueursRouteImport.update({
  id: '/marqueurs',
  path: '/marqueurs',
  getParentRoute: () => rootRouteImport,
} as any)
const OffreRoute = OffreRouteImport.update({
  id: '/offre',
  path: '/offre',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const PreuveRoute = PreuveRouteImport.update({
  id: '/preuve',
  path: '/preuve',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ShaRoute = ShaRouteImport.update({
  id: '/sha',
  path: '/sha',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceRoute = TraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CertifyRoute = ApiV1CertifyRouteImport.update({
  id: '/api/v1/certify',
  path: '/api/v1/certify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adopt': typeof AdoptRoute
  '/benchmark': typeof BenchmarkRoute
  '/blind': typeof BlindRoute
  '/certify': typeof CertifyRoute
  '/classes': typeof ClassesRoute
  '/corpus': typeof CorpusRoute
  '/falsify': typeof FalsifyRoute
  '/format': typeof FormatRoute
  '/goto': typeof GotoRoute
  '/invariants': typeof InvariantsRoute
  '/marqueurs': typeof MarqueursRoute
  '/offre': typeof OffreRoute
  '/patterns': typeof PatternsRoute
  '/preuve': typeof PreuveRoute
  '/rules': typeof RulesRoute
  '/sha': typeof ShaRoute
  '/tests': typeof TestsRoute
  '/tokens': typeof TokensRoute
  '/trace': typeof TraceRoute
  '/api/v1/certify': typeof ApiV1CertifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adopt': typeof AdoptRoute
  '/benchmark': typeof BenchmarkRoute
  '/blind': typeof BlindRoute
  '/certify': typeof CertifyRoute
  '/classes': typeof ClassesRoute
  '/corpus': typeof CorpusRoute
  '/falsify': typeof FalsifyRoute
  '/format': typeof FormatRoute
  '/goto': typeof GotoRoute
  '/invariants': typeof InvariantsRoute
  '/marqueurs': typeof MarqueursRoute
  '/offre': typeof OffreRoute
  '/patterns': typeof PatternsRoute
  '/preuve': typeof PreuveRoute
  '/rules': typeof RulesRoute
  '/sha': typeof ShaRoute
  '/tests': typeof TestsRoute
  '/tokens': typeof TokensRoute
  '/trace': typeof TraceRoute
  '/api/v1/certify': typeof ApiV1CertifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adopt': typeof AdoptRoute
  '/benchmark': typeof BenchmarkRoute
  '/blind': typeof BlindRoute
  '/certify': typeof CertifyRoute
  '/classes': typeof ClassesRoute
  '/corpus': typeof CorpusRoute
  '/falsify': typeof FalsifyRoute
  '/format': typeof FormatRoute
  '/goto': typeof GotoRoute
  '/invariants': typeof InvariantsRoute
  '/marqueurs': typeof MarqueursRoute
  '/offre': typeof OffreRoute
  '/patterns': typeof PatternsRoute
  '/preuve': typeof PreuveRoute
  '/rules': typeof RulesRoute
  '/sha': typeof ShaRoute
  '/tests': typeof TestsRoute
  '/tokens': typeof TokensRoute
  '/trace': typeof TraceRoute
  '/api/v1/certify': typeof ApiV1CertifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adopt'
    | '/benchmark'
    | '/blind'
    | '/certify'
    | '/classes'
    | '/corpus'
    | '/falsify'
    | '/format'
    | '/goto'
    | '/invariants'
    | '/marqueurs'
    | '/offre'
    | '/patterns'
    | '/preuve'
    | '/rules'
    | '/sha'
    | '/tests'
    | '/tokens'
    | '/trace'
    | '/api/v1/certify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adopt'
    | '/benchmark'
    | '/blind'
    | '/certify'
    | '/classes'
    | '/corpus'
    | '/falsify'
    | '/format'
    | '/goto'
    | '/invariants'
    | '/marqueurs'
    | '/offre'
    | '/patterns'
    | '/preuve'
    | '/rules'
    | '/sha'
    | '/tests'
    | '/tokens'
    | '/trace'
    | '/api/v1/certify'
  id:
    | '__root__'
    | '/'
    | '/adopt'
    | '/benchmark'
    | '/blind'
    | '/certify'
    | '/classes'
    | '/corpus'
    | '/falsify'
    | '/format'
    | '/goto'
    | '/invariants'
    | '/marqueurs'
    | '/offre'
    | '/patterns'
    | '/preuve'
    | '/rules'
    | '/sha'
    | '/tests'
    | '/tokens'
    | '/trace'
    | '/api/v1/certify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdoptRoute: typeof AdoptRoute
  BenchmarkRoute: typeof BenchmarkRoute
  BlindRoute: typeof BlindRoute
  CertifyRoute: typeof CertifyRoute
  ClassesRoute: typeof ClassesRoute
  CorpusRoute: typeof CorpusRoute
  FalsifyRoute: typeof FalsifyRoute
  FormatRoute: typeof FormatRoute
  GotoRoute: typeof GotoRoute
  InvariantsRoute: typeof InvariantsRoute
  MarqueursRoute: typeof MarqueursRoute
  OffreRoute: typeof OffreRoute
  PatternsRoute: typeof PatternsRoute
  PreuveRoute: typeof PreuveRoute
  RulesRoute: typeof RulesRoute
  ShaRoute: typeof ShaRoute
  TestsRoute: typeof TestsRoute
  TokensRoute: typeof TokensRoute
  TraceRoute: typeof TraceRoute
  ApiV1CertifyRoute: typeof ApiV1CertifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adopt': {
      id: '/adopt'
      path: '/adopt'
      fullPath: '/adopt'
      preLoaderRoute: typeof AdoptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blind': {
      id: '/blind'
      path: '/blind'
      fullPath: '/blind'
      preLoaderRoute: typeof BlindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certify': {
      id: '/certify'
      path: '/certify'
      fullPath: '/certify'
      preLoaderRoute: typeof CertifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpus': {
      id: '/corpus'
      path: '/corpus'
      fullPath: '/corpus'
      preLoaderRoute: typeof CorpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/falsify': {
      id: '/falsify'
      path: '/falsify'
      fullPath: '/falsify'
      preLoaderRoute: typeof FalsifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/format': {
      id: '/format'
      path: '/format'
      fullPath: '/format'
      preLoaderRoute: typeof FormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goto': {
      id: '/goto'
      path: '/goto'
      fullPath: '/goto'
      preLoaderRoute: typeof GotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invariants': {
      id: '/invariants'
      path: '/invariants'
      fullPath: '/invariants'
      preLoaderRoute: typeof InvariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marqueurs': {
      id: '/marqueurs'
      path: '/marqueurs'
      fullPath: '/marqueurs'
      preLoaderRoute: typeof MarqueursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offre': {
      id: '/offre'
      path: '/offre'
      fullPath: '/offre'
      preLoaderRoute: typeof OffreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preuve': {
      id: '/preuve'
      path: '/preuve'
      fullPath: '/preuve'
      preLoaderRoute: typeof PreuveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sha': {
      id: '/sha'
      path: '/sha'
      fullPath: '/sha'
      preLoaderRoute: typeof ShaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace': {
      id: '/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof TraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/certify': {
      id: '/api/v1/certify'
      path: '/api/v1/certify'
      fullPath: '/api/v1/certify'
      preLoaderRoute: typeof ApiV1CertifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdoptRoute: AdoptRoute,
  BenchmarkRoute: BenchmarkRoute,
  BlindRoute: BlindRoute,
  CertifyRoute: CertifyRoute,
  ClassesRoute: ClassesRoute,
  CorpusRoute: CorpusRoute,
  FalsifyRoute: FalsifyRoute,
  FormatRoute: FormatRoute,
  GotoRoute: GotoRoute,
  InvariantsRoute: InvariantsRoute,
  MarqueursRoute: MarqueursRoute,
  OffreRoute: OffreRoute,
  PatternsRoute: PatternsRoute,
  PreuveRoute: PreuveRoute,
  RulesRoute: RulesRoute,
  ShaRoute: ShaRoute,
  TestsRoute: TestsRoute,
  TokensRoute: TokensRoute,
  TraceRoute: TraceRoute,
  ApiV1CertifyRoute: ApiV1CertifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
